import type { ModelMetadata } from "./index";

/** Reviewed provider support, independent of application feature availability. */
export const MODEL_METADATA: Readonly<Record<string, ModelMetadata>> = {
  "anthropic:claude-fable-5-1": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: ["reasoning", "tools", "structured-output", "prompt-cache"],
    contextWindow: 1000000,
    sources: [
      "https://platform.claude.com/docs/en/models/overview",
      "https://platform.claude.com/docs/en/build-with-claude/pdf-support",
      "https://platform.claude.com/docs/en/build-with-claude/structured-outputs",
      "https://platform.claude.com/docs/en/build-with-claude/prompt-caching",
    ],
    reviewedAt: "2026-09-20",
  },
  "anthropic:claude-opus-5": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: ["reasoning", "tools", "structured-output", "prompt-cache"],
    contextWindow: 1000000,
    sources: [
      "https://platform.claude.com/docs/en/models/overview",
      "https://platform.claude.com/docs/en/build-with-claude/pdf-support",
      "https://platform.claude.com/docs/en/build-with-claude/structured-outputs",
      "https://platform.claude.com/docs/en/build-with-claude/prompt-caching",
    ],
    reviewedAt: "2026-09-20",
  },
  "anthropic:claude-sonnet-5": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: ["reasoning", "tools", "structured-output", "prompt-cache"],
    contextWindow: 1000000,
    sources: [
      "https://platform.claude.com/docs/en/models/overview",
      "https://platform.claude.com/docs/en/build-with-claude/pdf-support",
      "https://platform.claude.com/docs/en/build-with-claude/structured-outputs",
      "https://platform.claude.com/docs/en/build-with-claude/prompt-caching",
    ],
    reviewedAt: "2026-09-20",
  },
  "anthropic:claude-haiku-4-5": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: ["reasoning", "tools", "structured-output", "prompt-cache"],
    contextWindow: 200000,
    sources: [
      "https://platform.claude.com/docs/en/models/overview",
      "https://platform.claude.com/docs/en/build-with-claude/pdf-support",
      "https://platform.claude.com/docs/en/build-with-claude/structured-outputs",
      "https://platform.claude.com/docs/en/build-with-claude/prompt-caching",
    ],
    reviewedAt: "2026-09-20",
  },
  "anthropic:claude-opus-4-6": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: ["reasoning", "tools", "structured-output", "prompt-cache"],
    sources: [
      "https://platform.claude.com/docs/en/models/overview",
      "https://platform.claude.com/docs/en/build-with-claude/pdf-support",
      "https://platform.claude.com/docs/en/build-with-claude/structured-outputs",
      "https://platform.claude.com/docs/en/build-with-claude/prompt-caching",
    ],
    reviewedAt: "2026-09-20",
  },
  "anthropic:claude-sonnet-4-6": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: ["reasoning", "tools", "structured-output", "prompt-cache"],
    sources: [
      "https://platform.claude.com/docs/en/models/overview",
      "https://platform.claude.com/docs/en/build-with-claude/pdf-support",
      "https://platform.claude.com/docs/en/build-with-claude/structured-outputs",
      "https://platform.claude.com/docs/en/build-with-claude/prompt-caching",
    ],
    reviewedAt: "2026-09-20",
  },
  "openai:gpt-6-astra": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: [
      "reasoning",
      "tools",
      "structured-output",
      "prompt-cache",
      "web-search",
    ],
    contextWindow: 1050000,
    sources: [
      "https://developers.openai.com/api/docs/models/gpt-6-astra",
      "https://developers.openai.com/api/docs/guides/pdf-files",
    ],
    reviewedAt: "2026-09-20",
  },
  "openai:gpt-5.6-sol": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: [
      "reasoning",
      "tools",
      "structured-output",
      "prompt-cache",
      "web-search",
    ],
    contextWindow: 1050000,
    sources: [
      "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
      "https://developers.openai.com/api/docs/guides/pdf-files",
    ],
    reviewedAt: "2026-09-20",
  },
  "openai:gpt-5.6-terra": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: [
      "reasoning",
      "tools",
      "structured-output",
      "prompt-cache",
      "web-search",
    ],
    contextWindow: 1050000,
    sources: [
      "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
      "https://developers.openai.com/api/docs/guides/pdf-files",
    ],
    reviewedAt: "2026-09-20",
  },
  "openai:gpt-5.6-luna": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: [
      "reasoning",
      "tools",
      "structured-output",
      "prompt-cache",
      "web-search",
    ],
    contextWindow: 1050000,
    sources: [
      "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
      "https://developers.openai.com/api/docs/guides/pdf-files",
    ],
    reviewedAt: "2026-09-20",
  },
  "google:gemini-3.8-flash": {
    input: ["text", "image", "pdf", "audio", "video"],
    output: ["text"],
    features: [
      "reasoning",
      "tools",
      "structured-output",
      "prompt-cache",
      "web-search",
    ],
    contextWindow: 1048576,
    sources: ["https://ai.google.dev/gemini-api/docs/models/gemini-3.8-flash"],
    reviewedAt: "2026-09-20",
  },
  "google:gemini-3.1-pro-preview": {
    input: ["text", "image", "pdf", "audio", "video"],
    output: ["text"],
    features: [
      "reasoning",
      "tools",
      "structured-output",
      "prompt-cache",
      "web-search",
    ],
    contextWindow: 1048576,
    sources: [
      "https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview",
    ],
    reviewedAt: "2026-09-20",
  },
  "google:gemini-2.5-flash": {
    input: ["text", "image", "pdf", "audio", "video"],
    output: ["text"],
    features: [
      "reasoning",
      "tools",
      "structured-output",
      "prompt-cache",
      "web-search",
    ],
    contextWindow: 1048576,
    sources: ["https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash"],
    reviewedAt: "2026-09-20",
  },
  "xai:grok-4.6": {
    input: ["text", "image"],
    output: ["text"],
    features: [
      "reasoning",
      "tools",
      "structured-output",
      "prompt-cache",
      "web-search",
    ],
    contextWindow: 500000,
    sources: [
      "https://docs.x.ai/developers/grok-4-6",
      "https://docs.x.ai/developers/model-capabilities/text/structured-outputs",
    ],
    reviewedAt: "2026-09-20",
  },
  "deepseek:deepseek-flash": {
    input: ["text", "image"],
    output: ["text"],
    features: ["reasoning", "tools", "prompt-cache"],
    contextWindow: 1000000,
    sources: ["https://api-docs.deepseek.com/quick_start/pricing/"],
    reviewedAt: "2026-09-20",
  },
  "deepseek:deepseek-v4-pro": {
    input: ["text"],
    output: ["text"],
    features: ["reasoning", "tools", "prompt-cache"],
    contextWindow: 1000000,
    sources: ["https://api-docs.deepseek.com/quick_start/pricing/"],
    reviewedAt: "2026-09-20",
  },
  "mistral:mistral-medium-3-5": {
    input: ["text", "image", "pdf"],
    output: ["text"],
    features: ["reasoning", "tools", "structured-output"],
    contextWindow: 256000,
    sources: ["https://docs.mistral.ai/models/mistral-medium-3-5-26-04"],
    reviewedAt: "2026-09-20",
  },
  "moonshot:kimi-k3": {
    input: ["text", "image", "video"],
    output: ["text"],
    features: ["reasoning", "tools", "prompt-cache"],
    contextWindow: 1000000,
    sources: ["https://platform.kimi.ai/docs/guide/kimi-k3-quickstart"],
    reviewedAt: "2026-09-20",
  },
  "moonshot:kimi-k2.7-code": {
    input: ["text", "image", "video"],
    output: ["text"],
    features: ["reasoning", "tools", "prompt-cache"],
    contextWindow: 262144,
    sources: ["https://www.kimi.ai/resources/kimi-k2-7-code"],
    reviewedAt: "2026-09-20",
  },
  "meta:Llama-4-Maverick-17B-128E-Instruct-FP8": {
    input: ["text", "image"],
    output: ["text"],
    features: ["tools"],
    contextWindow: 1000000,
    sources: [
      "https://github.com/meta-llama/llama-models/blob/main/models/llama4/MODEL_CARD.md",
    ],
    reviewedAt: "2026-09-20",
  },
  "alibaba:qwen3.8-max": {
    input: ["text", "image", "video"],
    output: ["text"],
    features: ["reasoning", "tools", "prompt-cache"],
    contextWindow: 1000000,
    sources: ["https://help.aliyun.com/en/model-studio/qwen3-8-max"],
    reviewedAt: "2026-09-20",
  },
  "alibaba:qwen3.7-plus": {
    input: ["text", "image", "video"],
    output: ["text"],
    features: ["reasoning", "tools", "prompt-cache"],
    contextWindow: 1000000,
    sources: ["https://help.aliyun.com/en/model-studio/qwen3-7-plus"],
    reviewedAt: "2026-09-20",
  },
};

export const getModelMetadata = (
  provider: string,
  id: string,
): ModelMetadata | undefined => MODEL_METADATA[`${provider}:${id}`];
